routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();


Route::group(['middleware' => ['auth']], function () {
    Route::get('/user', [App\Http\Controllers\User\HomeController::class, 'index'])->name('user');
    Route::resource('user/order',App\Http\Controllers\User\OrderController::class);
    Route::get('user/myOrders',[App\Http\Controllers\User\OrderController::class,'create'])->name('myorders');
    Route::resource('user/myJobs',App\Http\Controllers\User\JobController::class);
    Route::resource('user/package',App\Http\Controllers\User\PackageController::class);


});

Route::group(['middleware' => ['isAdmin']], function () {
    Route::get('/admin', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('admin');

    Route::resource('admin/order',App\Http\Controllers\Admin\OrderController::class);
    Route::get('/admin/addOrder', [App\Http\Controllers\Admin\OrderController::class, 'create'])->name('addorder');
    Route::get('/admin/testOrder', [App\Http\Controllers\Admin\OrderController::class, 'test'])->name('test');
    Route::get('/admin/history', [App\Http\Controllers\Admin\OrderController::class, 'history'])->name('admin.orderHistory');


    Route::resource('admin/package',App\Http\Controllers\Admin\PackageController::class);

    Route::resource('admin/employee',App\Http\Controllers\Admin\EmployeeController::class);
    Route::resource('admin/jobOffer',App\Http\Controllers\Admin\JobController::class);
    Route::get("/admin/addPackage", function(){return view('admin.addPackage');});
    Route::get("/admin/addEmployee", function(){return view('admin.addEmployee');});
});

resources/views/admin/addEmployee.blade.php
@extends('layouts.admin.app')

@section('title','Add User')
@section('heading','Add User')

@section('content')
    <div class="col-md-12">
        <div class="card ">
            <div class="card-body ">
                {{--<form method="post" action="{{route('employee.store')}}" class="form-horizontal">--}}
                <form  class="form-horizontal">
                   {{-- @csrf--}}
                    <div class="row">
                        <label class="col-sm-2 col-form-label">First Name</label>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <input type="text" class="form-control" name="first_name">
                                <span class="form-text">Enter First Name..</span>
                            </div>
                        </div>
                        <label class="col-sm-2 col-form-label">Last Name</label>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <input type="text" class="form-control" name="last_name">
                                <span class="form-text">Enter Last Name..</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Type</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select  class="form-control" name="type">
                                    <option>Employee</option>
                                    <option>Contractor</option>
                                </select>
                                <span class="form-text">Select User Type..</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="email" class="form-control" name="email">
                                <span class="form-text">Enter email..</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Store</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" class="form-control" name="store">
                                <span class="form-text">Enter store name.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Store Info</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" class="form-control" name="store_info">
                                <span class="form-text">Enter store info.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Password</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" class="form-control" name="password">
                                <span class="form-text">Enter password.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/addOrder.blade.php
@extends('layouts.admin.app')

@section('title','Add Order')
@section('heading','Add Order')

@section('content')
<div class="col-md-12">
    <div class="card ">{{--
        <div class="card-header ">
            <h4 class="card-title">Add Order</h4>
        </div>--}}
        <div class="card-body ">
           {{-- <form method="post" action="{{route('order.store')}}" class="form-horizontal">--}}
            <form class="form-horizontal">
               {{-- @csrf--}}
                <div class="row">
                    <label class="col-sm-2 col-form-label">Package</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <select class="form-control" name="package">
                                <option selected>Select a Package</option>
                                @foreach ($packages as $package)
                                    <option value={{$package->id}}>{{$package->name}}</option>
                                @endforeach
                            </select>
                            <span class="form-text">Select a Package.</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Title</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="text" class="form-control" name="title">
                            <span class="form-text">Enter Title.</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Date</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="date" class="form-control" name="date">
                            <span class="form-text">Select Date.</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Start Time</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="time" class="form-control" name="startTime">
                            <span class="form-text">Select Starting Time.</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">End Time</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="time" class="form-control" name="endTime">
                            <span class="form-text">Select End Time.</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label class="col-sm-2 col-form-label">Address</label>
                    <div class="col-sm-10">
                        <div class="form-group">
                            <input type="text" class="form-control" name="address">
                            <span class="form-text">Enter address.</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 text-right">
                        <button type="submit" class="btn btn-primary">Add</button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/addPackage.blade.php
@extends('layouts.admin.app')

@section('title','Add Package')
@section('heading','Package')

@section('content')
    <div class="col-md-12">
        <div class="card ">{{--
            <div class="card-header ">
                <h4 class="card-title">Add Package</h4>
            </div>--}}
            <div class="card-body ">
               {{-- <form method="post" action="{{route('package.store')}}" class="form-horizontal">--}}
                <form class="form-horizontal">
                   {{-- @csrf--}}
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" class="form-control" name="name">
                                <span class="form-text">Enter a package name..</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Price</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" class="form-control" placeholder="$" min="0" name="price">
                                <span class="form-text">Enter price per hour.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Movers</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" class="form-control" name="movers">
                                <span class="form-text">Enter number of movers.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Trucks</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" class="form-control" name="truck">
                                <span class="form-text">Enter number of trucks.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Description</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <textarea class="form-control" name="description">  </textarea>
                                <span class="form-text">Enter Package Description.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">
                            <button type="submit" class="btn btn-primary">Add</button>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/employee.blade.php
@extends('layouts.admin.app')

@section('title','Users')
@section('heading','User List')

@section('content')
    <div class="col-md-12">
        <div class="card">{{--
            <div class="card-header">
                <h4 class="card-title"> Employee List</h4>
            </div>--}}
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                        <tr><th class="text-center">
                                #
                            </th>
                            <th>
                                User Name
                            </th>
                            <th>
                                Email
                            </th><th>
                                Store
                            </th>
                            <th>
                                Info
                            </th>
                            <th>
                                Type
                            </th>
                        </tr></thead>
                        <tbody>
                        <tr>
                            <td>1</td>
                            <td>John</td>
                            <td>John@user.com</td>
                            <td>Some store </td>
                            <td>Some Details</td>
                            <td>Employee</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>User</td>
                            <td>test@user.com</td>
                            <td>Some store </td>
                            <td>Some Details</td>
                            <td>Employee</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>User 2</td>
                            <td>test2@user.com</td>
                            <td>Some store2 </td>
                            <td>Some Details</td>
                            <td>Contractor</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>Test</td>
                            <td>test@test.com</td>
                            <td>Some test store </td>
                            <td>Some Details</td>
                            <td>Employee</td>
                        </tr>
                       {{-- @foreach($employees as $employee)
                            <tr>
                                <td>{{ $employee->id}}</td>
                                <td>{{ $employee->first_name}} {{ $employee->last_name}}</td>
                                <td>{{ $employee->email}}</td>
                                <td>{{ $employee->store}}</td>
                                <td>{{ $employee->store_info}}</td>
                            </tr>
                        @endforeach--}}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.admin.app')

@section('title','Dashboard')
@section('heading','Dashboard')
@section('content')
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-5 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-globe text-warning"></i>
                            </div>
                        </div>
                        <div class="col-7 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Current Orders</p>
                                <p class="card-title">150<p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">
                        <i class="fa fa-refresh"></i>
                        Update Now
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-5 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-money-coins text-success"></i>
                            </div>
                        </div>
                        <div class="col-7 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Revenue</p>
                                <p class="card-title">$ 1,345<p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">
                        <i class="fa fa-calendar-o"></i>
                        Last day
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-5 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-vector text-danger"></i>
                            </div>
                        </div>
                        <div class="col-7 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Errors</p>
                                <p class="card-title">23<p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">
                        <i class="fa fa-clock-o"></i>
                        In the last hour
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-body ">
                    <div class="row">
                        <div class="col-5 col-md-4">
                            <div class="icon-big text-center icon-warning">
                                <i class="nc-icon nc-favourite-28 text-primary"></i>
                            </div>
                        </div>
                        <div class="col-7 col-md-8">
                            <div class="numbers">
                                <p class="card-category">Total Orders</p>
                                <p class="card-title">+45K<p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">
                        <i class="fa fa-refresh"></i>
                        Update now
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/order.blade.php
@extends('layouts.admin.app')

@section('title','Order List')
@section('heading','Orders')

@section('content')
    <div class="col-md-12">
        <div class="card">
            <style>/* basic positioning */
                .legend { list-style: none; }
                .legend li { float: left; margin-right: 10px; }
                .legend span { border: 1px solid #ccc; float: left; width: 12px; height: 12px; margin: 2px; }
                /* your colors */
                .legend .superawesome { background-color: #B9F0B6; }
                .legend .awesome { background-color: #F7D321; }
                .legend .kindaawesome { background-color: #FFE8C2; }
                .legend .notawesome { background-color: #FFC2C2; }</style>
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <ul class="legend">
                            <li><span class="superawesome"></span>Open</li>
                            <li><span class="awesome"></span> Assigned</li>
                            <li><span class="kindaawesome"></span> Completed</li>
                            <li><span class="notawesome"></span> Cancelled</li>
                        </ul>
                        
                    </div>
            <div class="card-body">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div id="fullCalendar"></div>
                            <div id="data" style="display: none">{{$data}}</div>
                            <div id="packages" style="display: none">{$packages}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
<div class="modal fade" id="addOrder" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{route('order.store')}}" class="form-horizontal">
                    @csrf
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Package</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select class="form-control" name="package">
                                    <option selected>Select a Package</option>
                                    @foreach ($packages as $package)
                                        <option value={{$package->id}}>{{$package->name}}</option>
                                    @endforeach
                                </select>
                                <span class="form-text">Select a Package.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Title</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" class="form-control" name="title">
                                <span class="form-text">Enter Title.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Date</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input readonly type="text" class="form-control" id="id" name="date">
                                <span class="form-text">Select Date.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Start Time</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="time" class="form-control" name="startTime">
                                <span class="form-text">Select Starting Time.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">End Time</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="time" class="form-control" name="endTime">
                                <span class="form-text">Select End Time.</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Address</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" class="form-control" name="address">
                                <span class="form-text">Enter address.</span>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editOrder" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Manage Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                   {{-- @csrf--}}
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Package</label>
                        <div class="col-sm-10 col-form-label">
                            <div class="form-group">
                                <label class="pull-left">Premium Package</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Title</label>
                        <div class="col-sm-10 col-form-label">
                            <div class="form-group">
                                <label class="pull-left">Move Furniture</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Address</label>
                        <div class="col-sm-10 col-form-label">
                            <div class="form-group">
                                <label class="pull-left">Some Address</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">No. of Movers</label>
                        <div class="col-sm-10 col-form-label">
                            <div class="form-group">
                                <label class="pull-left">3</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">No. of Trucks</label>
                        <div class="col-sm-10 col-form-label">
                            <div class="form-group">
                                <label class="pull-left">1</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Job Requests</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <select class="form-control" name="Jobs">
                                    <option selected>Select Employee/Contractor</option>
                                    <option>Contractor 1</option>
                                    <option>Contractor 2</option>
                                    <option>Employee 1</option>
                                    <option>Contractor 3</option>
                                </select>
                                <span class="form-text">List of Job Requests.</span>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Assign Job</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/profile.blade.php
@extends('layouts.admin.app')

@section('title','Profile')
@section('heading','Profile')

@section('content')

@endsection